// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ozawokpiafoqqmzjxixq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96YXdva3BpYWZvcXFtemp4aXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NDI1OTYsImV4cCI6MjA4NzMxODU5Nn0.DqQ5MwFWkxC2115fpQ-1MqnNSiBleTfLtJDivx_FjsY";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);